<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fidd="http://www.sama.bea.sa/execution/services/FIDenyDlng"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="FIDenyDlng"
    targetNamespace="http://www.sama.bea.sa/execution/services/FIDenyDlng" xmlns:gai="http://www.sama.bea.sa/execution/services/FIDenyDlng"
    xmlns:head="http://www.sama.bea.sa/common/Header">

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.sama.bea.sa/execution/services/FIDenyDlng" schemaLocation="../services/FIDenyDlng.xsd" />
            <xsd:import namespace="http://www.sama.bea.sa/common/Header" schemaLocation="../../common/Header.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="FIDenyDlngRq">
        <wsdl:part element="gai:FIDenyDlngRq" name="parameters" />
    </wsdl:message>
    <wsdl:message name="FIDenyDlngRs">
        <wsdl:part element="gai:FIDenyDlngRs" name="parameters" />
    </wsdl:message>
    <wsdl:message name="RqHdr">
        <wsdl:part element="head:MsgHdrRq" name="header" />
    </wsdl:message>
    <wsdl:message name="RsHdr">
        <wsdl:part element="head:MsgHdrRs" name="header" />
    </wsdl:message>

    <wsdl:portType name="FIDenyDlng">
        <wsdl:operation name="FIDenyDlng">
            <wsdl:input message="fidd:FIDenyDlngRq" />
            <wsdl:output message="fidd:FIDenyDlngRs" />
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="FIDenyDlngSOAP" type="fidd:FIDenyDlng">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="FIDenyDlng">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <soap:header message="fidd:RqHdr" part="header" use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <soap:header message="fidd:RsHdr" part="header" use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="FIDenyDlng">
        <wsdl:port binding="fidd:FIDenyDlngSOAP" name="FIDenyDlngSOAP">
            <soap:address location="http://www.sama.bea.sa/" />
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>