<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:rpdd="http://www.sama.bea.sa/execution/services/RPDenyDlng"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="RPDenyDlng"
    targetNamespace="http://www.sama.bea.sa/execution/services/RPDenyDlng" xmlns:gai="http://www.sama.bea.sa/execution/services/RPDenyDlng"
    xmlns:head="http://www.sama.bea.sa/common/Header">

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.sama.bea.sa/execution/services/RPDenyDlng" schemaLocation="../services/RPDenyDlng.xsd" />
            <xsd:import namespace="http://www.sama.bea.sa/common/Header" schemaLocation="../../common/Header.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="RPDenyDlngRq">
        <wsdl:part element="gai:RPDenyDlngRq" name="parameters" />
    </wsdl:message>
    <wsdl:message name="RPDenyDlngRs">
        <wsdl:part element="gai:RPDenyDlngRs" name="parameters" />
    </wsdl:message>
    <wsdl:message name="RqHdr">
        <wsdl:part element="head:MsgHdrRq" name="header" />
    </wsdl:message>
    <wsdl:message name="RsHdr">
        <wsdl:part element="head:MsgHdrRs" name="header" />
    </wsdl:message>

    <wsdl:portType name="RPDenyDlng">
        <wsdl:operation name="RPDenyDlng">
            <wsdl:input message="rpdd:RPDenyDlngRq" />
            <wsdl:output message="rpdd:RPDenyDlngRs" />
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="RPDenyDlngSOAP" type="rpdd:RPDenyDlng">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="RPDenyDlng">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <soap:header message="rpdd:RqHdr" part="header" use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <soap:header message="rpdd:RsHdr" part="header" use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="RPDenyDlng">
        <wsdl:port binding="rpdd:RPDenyDlngSOAP" name="RPDenyDlngSOAP">
            <soap:address location="http://www.sama.bea.sa/" />
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>