create or replace TRIGGER AGCY_RQST_TRIG_UPD_STATUS 
AFTER UPDATE ON AGCY_SRVC_REQST 
REFERENCING NEW AS NEW 
FOR EACH ROW
BEGIN
  INSERT
INTO AGCY_SRVC_REQST_STATUS
  (
    AGCY_SRVC_REQST_STATUS_ID,
    AGCY_SRVC_REQST_ID,
    REQST_STATUS_CD,
    STATUS_CHANGE_TIME
  )
  VALUES
  (
    AGCY_SRVC_REQST_STAT_SEQ.NEXTVAL,
    :NEW.AGCY_SRVC_REQST_ID,
    :NEW.CURR_REQST_STATUS_CD,
    sysdate
  );
  
  if :NEW.CURR_REQST_STATUS_CD = 'RECIV' then 
    DELETE FROM ACTV_SLA_INSTANCE where SLA_INSTANCE_REF_ID = :NEW.AGCY_SRVC_REQST_ID;
  end if;
END;
