create or replace PROCEDURE ROUTING_VALIDATE_TRNS_SP 
(
  SP_CD IN VARCHAR2 
, SP_INPUT IN CLOB 
, RETURN_VAL OUT VARCHAR2 
) AS 

REF_DOC XMLTYPE;

BEGIN
  DBMS_OUTPUT.PUT_LINE('SP_CD>>>>' || SP_CD);
  REF_DOC := SYS.XMLTYPE.CREATEXML(SP_INPUT);

IF(SP_CD = GLOBAL_CONSTANTS.VALIDATE_BLOCK_DISPATCH_SP) then
	VALIDATE_BLOCK_DISPATCH_SP(REF_DOC, RETURN_VAL);
ELSIF (SP_CD = GLOBAL_CONSTANTS.VALIDATE_BAN_DISPATCH_SP) then
    VALIDATE_BAN_DISPATCH_SP(REF_DOC,RETURN_VAL);
ELSIF (SP_CD = GLOBAL_CONSTANTS.VALIDATE_DENY_DISPATCH_SP) then
    VALIDATE_DENY_DISPATCH_SP(REF_DOC, RETURN_VAL);
ELSIF (SP_CD = GLOBAL_CONSTANTS.VALIDATE_LIFT_DISPATCH_SP) then
    VALIDATE_LIFT_DISPATCH_SP(REF_DOC, RETURN_VAL);
ELSIF (SP_CD = GLOBAL_CONSTANTS.VALIDATE_GARNISH_DISPATCH_SP) then
    VALIDATE_GARNISH_DISPATCH_SP(REF_DOC);
    ELSIF (SP_CD = GLOBAL_CONSTANTS.VALIDATE_GI_DISPATCH_SP) then
    VALIDATE_GI_DISPATCH_SP(REF_DOC,RETURN_VAL);
      ELSIF (SP_CD = GLOBAL_CONSTANTS.VALIDATERPLIFT) then
    VALIDATERPLIFT(REF_DOC,RETURN_VAL);
    
ELSE
    Raise_application_error(-20322, 'INVALID SERVICE CODE');
 END IF;
EXCEPTION
	WHEN OTHERs THEN
		Raise_application_error(-20322, 'UNKNOWN ERROR>>'|| SQLERRM); 
END ROUTING_VALIDATE_TRNS_SP;