CREATE OR REPLACE TRIGGER EXEC_SUMMARY_UPD_TRIG 
AFTER UPDATE ON EXEC_SUMMARY 
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN


  IF :NEW.STATUS = 'LFT' then
  
  Delete from EXEC_RUNNING_TOTALS where EXEC_SUMMARY_ID = :NEW.EXEC_SUMMARY_ID;
  
  END IF;
END;